---
- name: "install python3 venv"
  apt:
    name: "python3-venv"
    state: "present"

- name: "create venv"
  command:
    cmd: python3 -m venv envdg
    creates: envdg
    chdir: /home/ubuntu

- name: "install django"
  shell:
    pip install django

- name: "install website"
  git:
    repo: "https://github.com/Godot-dev/django-ansible"
    dest: /home/ubuntu/django-ansible

- name: "launch website"
  shell:
    cd django-ansible/mysite
    /home/ubuntu/envdg/bin/python3 manage.py runserver
  args:
    chdir: /home/ubuntu