---
- name: "install python3 venv"
  apt:
    name: "python3-venv"
    state: "present"

- name: "create venv"
  command:
    cmd: python3 -m venv {{venv_name}}
    creates: "{{venv_name}}"
    chdir: /home/{{vm_user}}

- name: "install django"
  shell:
    ./pip install django
  args:
    chdir: /home/{{vm_user}}/{{venv_name}}/bin

- name: "install website"
  git:
    repo: "{{git_repo_link}}"
    dest: /home/{{vm_user}}/{{git_repo_name}}