---
- name: "install python3 venv"
  apt:
    name: "python3-venv"
    state: "present"

- name: "create and launch venv"
  shell:
    python3 -m venv envdg & chmod +x envdg/bin/activate & ./envdg/bin/activate
  args:
    chdir: /home/ubuntu


- name: "install django"
  shell:
    pip install django

- name: "install website"
  git:
    repo: "https://github.com/Godot-dev/django-ansible"
    dest: /home/ubuntu/django-ansible

- name: "launch website"
  shell:
    cd django-ansible/mysite
    python3 manage.py runserver
  args:
    chdir: /home/ubuntu