---
- name: "upgrade and update apt"
  apt:
    upgrade: full

- name: "install dependencies"
  apt:
    pkg: 
      - postgresql 
      - postgresql-contrib
      - python3-pip
      - acl
    state: "present"

- name: "install psycopg2 (postgresql python library)"
  shell:
    pip install psycopg2-binary

- name: Set listen parameter
  become_user: postgres
  community.postgresql.postgresql_set:
    name: "listen_addresses"
    value: "*"

- name: Autoriser l'accès PostgreSQL depuis le serveur django
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    users: all
    databases: all
    address: "{{djangoserver_ip}}/32"
    #method: md5

- name: "activation postgresql"
  service:
    name: "postgresql"
    state: "restarted"
    enabled: yes

- name: "Create a new database"
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{db_name}}"

- name: "Connect to database, create django user, and grant access to database and products table"
  become_user: postgres
  community.postgresql.postgresql_user:
    login_db: "{{db_name}}"
    name: "{{db_user}}"
    password: "{{db_password}}"
    expires: "Jan 31 2027"