---
- name: "upgrade and update apt"
  apt:
    upgrade: full

- name: "install dependencies"
  apt:
    pkg: 
      - postgresql 
      - postgresql-contrib
      - python3-pip
    state: "present"

- name: "install psycopg2 (postgresql python library)"
  shell:
    pip install psycopg2-binary

- name: "activation postgresql"
  service:
    name: "postgresql"
    state: "restarted"
    enabled: yes

- name: "Create a new database"
  community.postgresql.postgresql_db:
    name: "{{db_name}}"

- name: "Connect to database, create django user, and grant access to database and products table"
  community.postgresql.postgresql_user:
    login_db: "{{db_name}}"
    name: "{{db_user}}"
    password: "{{db_password}}"
    expires: "Jan 31 2027"

- name: "update settings.py"
  ansible.builtin.blockinfile:
    path: /home/ubuntu/django-ansible/my-site/my-site/settings.py
    block: |
      DATABASES[default] = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "{{db_name}}",
        "USER": "{{db_user}}",
        "PASSWORD": "{{db_password}}",
        "HOST": "{{db_host}}",
        "PORT": "{{db_port}}",
      }