---
- name: "upgrade and update apt"
  apt:
    upgrade: full

- name: "install dependencies"
  apt:
    pkg: 
      - postgresql 
      - postgresql-contrib
      - python3-pip
      - acl
    state: "present"

- name: "install psycopg2 (postgresql python library)"
  shell:
    pip install psycopg2-binary

- name: "activation postgresql"
  service:
    name: "postgresql"
    state: "restarted"
    enabled: yes

- name: "Create a new database"
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{db_name}}"

- name: "Connect to database, create django user, and grant access to database and products table"
  become_user: postgres
  community.postgresql.postgresql_user:
    login_db: "{{db_name}}"
    name: "{{db_user}}"
    password: "{{db_password}}"
    expires: "Jan 31 2027"