---

- name: "install and launch website"
  hosts: django
  become: yes
  roles :
    - role: "django"

- name: "installation bdd"
  hosts: bdd
  become: yes
  become_user: postgres
  roles :
    - role: "bdd"

- name: "launch website"
  hosts: django
  tasks:
    - name: import variables
      import_role:
        name: common
    - name: "make db migrations"
      become: yes
      become_user: postgres
      shell: |
        /home/{{vm_user}}/{{venv_name}}/bin/python3 manage.py makemigrations 
        /home/{{vm_user}}/{{venv_name}}/bin/python3 manage.py migrate
      args:
        chdir: /home/{{vm_user}}/{{git_repo_name}}/{{git_repo_directory}}

    - name: "runserver"
      shell:
        nohup /home/{{vm_user}}/{{venv_name}}/bin/python3 manage.py runserver 0.0.0.0:8000 &
      args:
        chdir: /home/{{vm_user}}/{{git_repo_name}}/{{git_repo_directory}}
