---
- name: "mandatory variables verification"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: verify that variables 'install' et 'launch' are defined
      assert:
        that:
          - install is defined
          - launch is defined
        fail_msg: "variables 'install' et 'launch'are mandatory. Use -e install=true launch=false"

- name: "website installation"
  hosts: django
  become: yes
  when: install == true
  roles :
    - role: "install-web"

- name: "database installation"
  hosts: bdd
  become: yes
  when: install == true
  roles :
    - role: "install-db"

- name: "launch website"
  hosts: django
  when: launch == true
  roles :
    - role: "launch-web"
    
