---
# git
git_repo_link: "https://github.com/Godot-dev/django-ansible"
git_repo_name: "django-ansible"
# For practical reasons, the ansible deployment and the django app directory are in the same repo
git_repo_directory: "mysite"

# django
venv_name: "django"
site_path: "/home/{{ansible_user}}/{{git_repo_name}}/{{git_repo_directory}}"
venv_path: /home/{{ansible_user}}/{{venv_name}}/bin
manage_path: /home/{{ansible_user}}/{{git_repo_name}}/{{git_repo_directory}}